packages:
- '.'
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: 9e4e5e5805bccd28b9254c9a286fe384aee69ce2
  extra-dep: True
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 962c2fc42194eaf3f53e5399df1ca679974a270e
  extra-dep: True
- location:
    git: https://github.com/lamdu/graphics-drawingcombinators
    commit: 82f70c03a632402eb32d9e3bbb3fdd9a32492bd5
  extra-dep: True
- location:
    git: https://github.com/lamdu/freetype2
    commit: 046328d92312d65638440132c016a3081d9c32a4
  extra-dep: True
- location:
    git: https://github.com/lamdu/bindings-freetype-gl
    commit: 3e409dd8c5232abc53fd10e8138658333b90456f
  extra-dep: True
- location:
    git: https://github.com/lamdu/leveldb-haskell
    commit: 6f2f0b88fd7197e74cbff92bde94168adce3fb29
  extra-dep: True
- location:
    git: https://github.com/lamdu/FreetypeGL
    commit: d2312f89cdf1412d584d13cda235ef683fa9c832
  extra-dep: True
- location:
    git: https://github.com/lamdu/nodejs-exec
    commit: 6a8b5c7897b822f523414fe2c0e666ecb8d4ab4b
  extra-dep: True
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0

resolver: lts-13.15

flags:
  Lamdu:
    ekg: false

allow-newer: true

